# Generated by Django 5.0.6 on 2024-07-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptesis', '0002_proyecto_obra_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='es_primero',
            field=models.BooleanField(default=False),
        ),
    ]
