# Generated by Django 5.0.6 on 2024-07-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptesis', '0003_obra_es_primero'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='deuda',
            field=models.IntegerField(default=0),
        ),
    ]
